openapi: 3.1.0
info:
  title: Serviço de Entidade - Curso API
  description: Gestão de Cursos no Sistema de Matrícula
  contact:
    name: Vicente Jr., Brenno Ribeiro e Rosane Pinheiro
    email: juniorvf@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: /api/Curso

paths:
  /cursos:
    get:
      summary: Lista todos os cursos
      operationId: listarCursos
      parameters:
        - name: _count
          in: query
          description: Quantidade de registros a retornar
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
        - name: _offset
          in: query
          description: Quantidade de registros a pular (paginação)
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchSet'
    post:
      summary: Cria um novo curso
      operationId: criarCurso
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/curso.v1.json'
      responses:
        "201":
          description: Curso criado com sucesso
          content:
            application/json:
              schema:
                $ref: '../schemas/curso.v1.json'
        "400":
          description: Erro de negócio
          content:
            application/json:
              schema:
                $ref: '../schemas/erro_api.v1.json'
        "422":
          description: Erro de validação
          content:
            application/json:
              schema:
                $ref: '../schemas/erro_api.v1.json'

  /cursos/{id}:
    get:
      summary: Obtém detalhes de um curso
      operationId: obterCurso
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '../schemas/curso.v1.json'
        "404":
          description: Curso não encontrado
          content:
            application/json:
              schema:
                $ref: '../schemas/erro_api.v1.json'
    put:
      summary: Atualiza um curso existente
      operationId: atualizarCurso
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/curso.v1.json'
      responses:
        "200":
          description: Curso atualizado
          content:
            application/json:
              schema:
                $ref: '../schemas/curso.v1.json'
        "404":
          description: Curso não encontrado
          content:
            application/json:
              schema:
                $ref: '../schemas/erro_api.v1.json'

components:
  schemas:

    Resource:
      type: object
      required:
        - resourceType
      properties:
        id:
          type: string
          description: id único da instânica
        resourceType:
          type: string
        lastUpdated:
          type: string
          format: date-time
      discriminator:
        propertyName: resourceType
        mapping:
          Aluno: '#/components/schemas/Aluno'
          Curso: '#/components/schemas/Curso'
          Curriculo: '#/components/schemas/Curriculo'
          Disciplina: '#/components/schemas/Disciplina'
          Docente: '#/components/schemas/Docente'
          HistoricoAcademico: '#/components/schemas/HistoricoAcademico'
          Matricula: '#/components/schemas/Matricula'
          Turma: '#/components/schemas/Turma'
          UnidadeOrganizacional: '#/components/schemas/UnidadeOrganizacional'

    SearchSet:
      type: object  
      required:
        - total
        - link
      properties:
        total:
          type: integer 
        count:
          type: integer
        offset:
          type: integer     
        link:
          type: object
          required:
            - self
          properties:
            self:
              type: string
            next:
              type: string
            previous:
              type: string
        items:
          type: array
          items:
            anyOf:
            - $ref: '#/components/schemas/AlunoResponse'
            - $ref: '#/components/schemas/CursoResponse'
            - $ref: '#/components/schemas/CurriculoResponse'
            - $ref: '#/components/schemas/DisciplinaResponse'
            - $ref: '#/components/schemas/DocenteResponse'
            - $ref: '#/components/schemas/HistoricoAcademicoResponse'
            - $ref: '#/components/schemas/MatriculaResponse'
            - $ref: '#/components/schemas/TurmaResponse'
            - $ref: '#/components/schemas/UnidadeOrganizacionalResponse'
