openapi: 3.0.3
info:
  title: Serviço de Entidade - Curso API
  description: Gestão de Cursos no Sistema de Matrícula - Entrega 1 (Reduzida)
  contact:
    name: Vicente Jr., Brenno Ribeiro e Rosane Pinheiro
    email: juniorvf@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: /api/Curso

tags:
  - name: Curso
    description: Curso de graduação da Universidade de Brasília

paths:
  /:
    get:
      tags:
        - Curso
      summary: Pesquisa cursos.
      description: Pesquisa cursos cadastrados.
      operationId: search
      parameters:
        - name: nome
          in: query
          description: Nome (ou parte do nome) do curso
          required: false
          schema:
            type: string
        - name: unidade
          in: query
          description: ID ou código da unidade organizacional
          required: false
          schema:
            type: string
        - name: sede
          in: query
          description: Campus ou sede do curso
          required: false
          schema:
            type: string
        - name: _count
          in: query
          description: Quantidade de registros a retornar
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
        - name: _offset
          in: query
          description: Quantidade de registros a pular (paginação)
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchSet'
        '400':
          description: Erro de validação ou negócio
          content:
            application/json:
              schema:
                $ref: '../../schemas/erro_api.v1.json'

  /{id}:
    get:
      tags:
        - Curso
      summary: Consulta um curso.
      description: Consulta um curso pelo seu ID.
      operationId: read
      parameters:
        - name: id
          in: path
          description: Identificador do curso
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Curso'
        '404':
          description: Curso não encontrado
          content:
            application/json:
              schema:
                $ref: '../../schemas/erro_api.v1.json'

components:
  schemas:
    Resource:
      type: object
      required:
        - resourceType
      properties:
        id:
          type: string
          description: id único da instância
        resourceType:
          type: string
        lastUpdated:
          type: string
          format: date-time
      discriminator:
        propertyName: resourceType
        mapping:
          Curso: '#/components/schemas/Curso'

    Curso:
      allOf:
        - $ref: '#/components/schemas/Resource'
        - $ref: '../../schemas/curso.v1.json'

    Curso_Short:
      allOf:
        - $ref: '#/components/schemas/Resource'
        - type: object
          properties:
            id:
              type: string
              example: '6351'
            codigo:
              type: string
              example: '6351'
            nome:
              type: string
              example: "ENGENHARIA DE REDES DE COMUNICAÇÃO"

    SearchSet:
      type: object
      required:
        - total
        - link
      properties:
        total:
          type: integer
        count:
          type: integer
        offset:
          type: integer
        link:
          type: object
          required:
            - self
          properties:
            self:
              type: string
            next:
              type: string
            previous:
              type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/Curso_Short'
