"""Add historicos_academicos table

Revision ID: 004401650ca4
Revises: 7b67b775421e
Create Date: 2026-04-24 17:33:52.196285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004401650ca4'
down_revision: Union[str, Sequence[str], None] = '7b67b775421e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historicos_academicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('periodo_letivo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('APROVADO', 'REPROVADO', 'TRANCADO', 'CURSANDO', name='statushistorico'), nullable=False),
    sa.Column('nota_final', sa.Float(), nullable=True),
    sa.Column('aprovado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['periodo_letivo_id'], ['periodos_letivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historicos_academicos_id'), 'historicos_academicos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historicos_academicos_id'), table_name='historicos_academicos')
    op.drop_table('historicos_academicos')
    # ### end Alembic commands ###
