"""Create Usuario table

Revision ID: 768178c61369
Revises: a1b2c3d4e5f6
Create Date: 2026-05-01 23:04:33.969202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '768178c61369'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ALUNO', 'COORDENACAO', 'PROCESSAMENTO', 'CONSULTA', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    
    # Inserir Seed Data
    from app.core.security import get_password_hash
    
    admin_pw = get_password_hash('admin')
    aluno_pw = get_password_hash('aluno')
    coord_pw = get_password_hash('coord')
    proc_pw = get_password_hash('proc')
    cons_pw = get_password_hash('cons')
    
    op.execute(f"INSERT INTO usuarios (id, username, hashed_password, role, is_active) VALUES ('1001', 'admin', '{admin_pw}', 'ADMIN', true);")
    op.execute(f"INSERT INTO usuarios (id, username, hashed_password, role, is_active) VALUES ('1002', 'aluno', '{aluno_pw}', 'ALUNO', true);")
    op.execute(f"INSERT INTO usuarios (id, username, hashed_password, role, is_active) VALUES ('1003', 'coordenacao', '{coord_pw}', 'COORDENACAO', true);")
    op.execute(f"INSERT INTO usuarios (id, username, hashed_password, role, is_active) VALUES ('1004', 'processamento', '{proc_pw}', 'PROCESSAMENTO', true);")
    op.execute(f"INSERT INTO usuarios (id, username, hashed_password, role, is_active) VALUES ('1005', 'consulta', '{cons_pw}', 'CONSULTA', true);")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
