"""Add disciplinas and turmas

Revision ID: 7b67b775421e
Revises: 793f3fd0acbb
Create Date: 2026-04-23 12:52:23.078748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b67b775421e'
down_revision: Union[str, Sequence[str], None] = '793f3fd0acbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodos_letivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periodos_letivos_codigo'), 'periodos_letivos', ['codigo'], unique=True)
    op.create_index(op.f('ix_periodos_letivos_id'), 'periodos_letivos', ['id'], unique=False)
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('carga_horaria', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciplinas_codigo'), 'disciplinas', ['codigo'], unique=True)
    op.create_index(op.f('ix_disciplinas_id'), 'disciplinas', ['id'], unique=False)
    op.create_table('disciplinas_prerequisitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('prerequisito_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['prerequisito_id'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciplinas_prerequisitos_id'), 'disciplinas_prerequisitos', ['id'], unique=False)
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('periodo_letivo_id', sa.Integer(), nullable=False),
    sa.Column('codigo_turma', sa.String(length=10), nullable=False),
    sa.Column('vagas_totais', sa.Integer(), nullable=False),
    sa.Column('vagas_ocupadas', sa.Integer(), nullable=False),
    sa.Column('horario_serializado', sa.String(length=200), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['periodo_letivo_id'], ['periodos_letivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turmas_id'), 'turmas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turmas_id'), table_name='turmas')
    op.drop_table('turmas')
    op.drop_index(op.f('ix_disciplinas_prerequisitos_id'), table_name='disciplinas_prerequisitos')
    op.drop_table('disciplinas_prerequisitos')
    op.drop_index(op.f('ix_disciplinas_id'), table_name='disciplinas')
    op.drop_index(op.f('ix_disciplinas_codigo'), table_name='disciplinas')
    op.drop_table('disciplinas')
    op.drop_index(op.f('ix_periodos_letivos_id'), table_name='periodos_letivos')
    op.drop_index(op.f('ix_periodos_letivos_codigo'), table_name='periodos_letivos')
    op.drop_table('periodos_letivos')
    # ### end Alembic commands ###
