"""baseline_sigaa_schema

Autores: Vicente Jr., Brenno Ribeiro e Rosane
Disciplina: Segurança em Sistemas Distribuídos — UnB (Prof. Ricardo Puttini)

Baseline único que cria as 17 tabelas do modelo de dados SIGAA fornecido pelo
professor (SIGAA_UNIDADE, SIGAA_DISCIPLINA, SIGAA_PREREQ, SIGAA_CURSO,
SIGAA_RL_CURSO_UNIDADE, SIGAA_CURRICULO, SIGAA_RL_CURRICULO_CURSO,
SIGAA_RL_CURRICULO_DISCIPLINA, SIGAA_TURMA_HORARIOAULA, SIGAA_TURMA,
SIGAA_RL_TURMA_HORARIOAULA, SIGAA_ALUNO, SIGAA_RL_ALUNO_CURSO,
SIGAA_RL_ALUNO_CURSO_DISCIPLINA, SIGAA_MATRICULA_STATUS, SIGAA_MATRICULA,
SIGAA_MATRICULA_HISTORICO). Substitui o histórico de migrations do modelo antigo.

Revision ID: a4cb4bb91965
Revises:
Create Date: 2026-07-06 10:42:30.408662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4cb4bb91965'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sigaa_aluno',
    sa.Column('matricula', sa.String(length=9), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('matricula')
    )
    op.create_table('sigaa_curriculo',
    sa.Column('id', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('periodo_letivo_vigor', sa.String(length=5), nullable=False),
    sa.Column('carga_horaria_minima_total', sa.Numeric(precision=5, scale=0), nullable=False),
    sa.Column('carga_horaria_minima_opt', sa.Numeric(precision=5, scale=0), nullable=False),
    sa.Column('carga_horaria_obr', sa.Numeric(precision=5, scale=0), nullable=False),
    sa.Column('carga_horaria_eletiva_max', sa.Numeric(precision=5, scale=0), nullable=False),
    sa.Column('carga_horaria_max_periodo', sa.Numeric(precision=5, scale=0), nullable=False),
    sa.Column('num_periodos', sa.Numeric(precision=2, scale=0), nullable=False),
    sa.Column('min_periodos', sa.Numeric(precision=2, scale=0), nullable=False),
    sa.Column('max_periodos', sa.Numeric(precision=2, scale=0), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sigaa_curso',
    sa.Column('id', sa.String(length=4), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('grau_academico', sa.String(length=15), nullable=False),
    sa.Column('turno', sa.String(length=10), nullable=False),
    sa.Column('modalidade', sa.String(length=25), nullable=False),
    sa.Column('coordenador', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sigaa_matricula_status',
    sa.Column('id', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sigaa_turma_horarioaula',
    sa.Column('id', sa.String(length=3), nullable=False),
    sa.Column('dia', sa.String(length=3), nullable=False),
    sa.Column('hora_inicio', sa.String(length=5), nullable=False),
    sa.Column('hora_fim', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dia', 'hora_inicio', 'hora_fim', name='horarioaula_unique')
    )
    op.create_table('sigaa_unidade',
    sa.Column('id', sa.String(length=3), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sigaa_disciplina',
    sa.Column('id', sa.String(length=7), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('modalidade', sa.String(length=50), nullable=True),
    sa.Column('carga_horaria_teorica', sa.Numeric(precision=3, scale=0), nullable=True),
    sa.Column('carga_horaria_pratica', sa.Numeric(precision=3, scale=0), nullable=True),
    sa.Column('unidade', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['unidade'], ['sigaa_unidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sigaa_rl_aluno_curso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aluno', sa.String(length=9), nullable=False),
    sa.Column('curso', sa.String(length=4), nullable=False),
    sa.Column('curriculo', sa.String(length=7), nullable=False),
    sa.Column('data_registro', sa.Date(), nullable=False),
    sa.Column('periodo_letivo_registro', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('ira', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['aluno'], ['sigaa_aluno.matricula'], ),
    sa.ForeignKeyConstraint(['curriculo'], ['sigaa_curriculo.id'], ),
    sa.ForeignKeyConstraint(['curso'], ['sigaa_curso.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno', 'curso', 'periodo_letivo_registro', name='aluno_curso_unique')
    )
    op.create_table('sigaa_rl_curriculo_curso',
    sa.Column('curriculo', sa.String(length=7), nullable=False),
    sa.Column('curso', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['curriculo'], ['sigaa_curriculo.id'], ),
    sa.ForeignKeyConstraint(['curso'], ['sigaa_curso.id'], ),
    sa.PrimaryKeyConstraint('curriculo', 'curso')
    )
    op.create_table('sigaa_rl_curso_unidade',
    sa.Column('curso', sa.String(length=4), nullable=False),
    sa.Column('unidade', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['curso'], ['sigaa_curso.id'], ),
    sa.ForeignKeyConstraint(['unidade'], ['sigaa_unidade.id'], ),
    sa.PrimaryKeyConstraint('curso', 'unidade')
    )
    op.create_table('sigaa_matricula_historico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aluno_curso', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=3), nullable=False),
    sa.Column('turma', sa.Integer(), nullable=False),
    sa.Column('prioridade', sa.Numeric(precision=2, scale=0), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aluno_curso'], ['sigaa_rl_aluno_curso.id'], ),
    sa.ForeignKeyConstraint(['status'], ['sigaa_matricula_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sigaa_prereq',
    sa.Column('disciplina_requer', sa.String(length=7), nullable=False),
    sa.Column('disciplina_requerido', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_requer'], ['sigaa_disciplina.id'], ),
    sa.ForeignKeyConstraint(['disciplina_requerido'], ['sigaa_disciplina.id'], ),
    sa.PrimaryKeyConstraint('disciplina_requer', 'disciplina_requerido')
    )
    op.create_table('sigaa_rl_aluno_curso_disciplina',
    sa.Column('aluno_curso', sa.Integer(), nullable=False),
    sa.Column('disciplina', sa.String(length=7), nullable=False),
    sa.Column('periodo_letivo', sa.String(length=5), nullable=False),
    sa.Column('mencao', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['aluno_curso'], ['sigaa_rl_aluno_curso.id'], ),
    sa.ForeignKeyConstraint(['disciplina'], ['sigaa_disciplina.id'], ),
    sa.PrimaryKeyConstraint('aluno_curso', 'disciplina', 'periodo_letivo')
    )
    op.create_table('sigaa_rl_curriculo_disciplina',
    sa.Column('curriculo', sa.String(length=7), nullable=False),
    sa.Column('disciplina', sa.String(length=7), nullable=False),
    sa.Column('periodo', sa.Numeric(precision=2, scale=0), nullable=True),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['curriculo'], ['sigaa_curriculo.id'], ),
    sa.ForeignKeyConstraint(['disciplina'], ['sigaa_disciplina.id'], ),
    sa.PrimaryKeyConstraint('curriculo', 'disciplina')
    )
    op.create_table('sigaa_turma',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=2), nullable=False),
    sa.Column('periodo_letivo', sa.String(length=5), nullable=False),
    sa.Column('disciplina', sa.String(length=7), nullable=False),
    sa.Column('vagas', sa.Numeric(precision=3, scale=0), nullable=True),
    sa.Column('sede', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['disciplina'], ['sigaa_disciplina.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', 'periodo_letivo', 'disciplina', name='turma_unique')
    )
    op.create_table('sigaa_matricula',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aluno_curso', sa.Integer(), nullable=False),
    sa.Column('turma', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=3), nullable=False),
    sa.Column('prioridade', sa.Numeric(precision=2, scale=0), nullable=True),
    sa.ForeignKeyConstraint(['aluno_curso'], ['sigaa_rl_aluno_curso.id'], ),
    sa.ForeignKeyConstraint(['status'], ['sigaa_matricula_status.id'], ),
    sa.ForeignKeyConstraint(['turma'], ['sigaa_turma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sigaa_rl_turma_horarioaula',
    sa.Column('turma', sa.Integer(), nullable=False),
    sa.Column('horarioaula', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['horarioaula'], ['sigaa_turma_horarioaula.id'], ),
    sa.ForeignKeyConstraint(['turma'], ['sigaa_turma.id'], ),
    sa.PrimaryKeyConstraint('turma', 'horarioaula'),
    sa.UniqueConstraint('horarioaula', 'turma', name='turma_haula_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sigaa_rl_turma_horarioaula')
    op.drop_table('sigaa_matricula')
    op.drop_table('sigaa_turma')
    op.drop_table('sigaa_rl_curriculo_disciplina')
    op.drop_table('sigaa_rl_aluno_curso_disciplina')
    op.drop_table('sigaa_prereq')
    op.drop_table('sigaa_matricula_historico')
    op.drop_table('sigaa_rl_curso_unidade')
    op.drop_table('sigaa_rl_curriculo_curso')
    op.drop_table('sigaa_rl_aluno_curso')
    op.drop_table('sigaa_disciplina')
    op.drop_table('sigaa_unidade')
    op.drop_table('sigaa_turma_horarioaula')
    op.drop_table('sigaa_matricula_status')
    op.drop_table('sigaa_curso')
    op.drop_table('sigaa_curriculo')
    op.drop_table('sigaa_aluno')
    # ### end Alembic commands ###
