openapi: 3.0.4
info:
  title: Aluno
  description: >-
    API para tratamento de informações dos Alunos de graduação da Universidade de Brasília (UnB)
  termsOfService: https://redes.unb.br/api/terms/
  contact:
    email: ricardo.puttini@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
  - url: /api/Aluno
tags:
  - name: Aluno
    description: Aluno de graduação da Universidade de Brasília
paths:
  /:
    get:
      tags:
        - Aluno
      summary: Pesquisa alunos.
      description: Pesquisa alunos por nome, período letivo de ingresso e curso.
      operationId: search
      parameters:
        - name: nome
          in: query
          description: Nome (ou parte do nome) do aluno
          required: false
          schema:
            type: string
        - name: curso
          in: query
          description: Curso (codigo do curso) do aluno
          required: false
          schema:
            type: string
        - name: curriculo
          in: query
          description: Currículo (codigo do currículo) do aluno
          required: false
          schema:
            type: string
        - name: periodoIngresso
          in: query
          description: Período letivo do ingresso do aluno, no formato AAAA-N por exemplo, 2024-1
          required: false
          schema:
            type: string
        - name: _count
          in: query
          description: quantidade de registros retornados
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10    
        - name: _offset
          in: query
          description: quantidade de registros retornados
          schema:
            type: integer    
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchSet'
  /{id}:
    get:
      tags:
        - Aluno
      summary: Consulta um aluno.
      description: Consulta um aluno pelo seu id (matricula).
      operationId: read
      parameters:
        - name: id
          in: path
          description: id (matricula) do aluno
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aluno'
        '404':
          description: not found
components:
  schemas:
    Aluno:
      allOf: 
        - $ref: '#/components/schemas/Resource'
        - type: object
          properties:
            id:
              example: 252100019
            matricula:
              type: string
              example: 252100019
            nome:
              type: string
              example: RICARDO STACIARINI PUTTINI
            ira:
              type: number
              example: 3.9
            periodoIngresso:
              $ref: '#/components/schemas/PeriodoLetivo'
            curso:
              $ref: "#/components/schemas/Curso_Short" 
            curriculo:
              $ref: '#/components/schemas/Curriculo_Short'     
    Aluno_Short:
      allOf: 
        - $ref: '#/components/schemas/Resource'
        - type: object
          properties:
            id:
              type: string
              example: 252100019
            matricula:
              type: string
              example: 252100019
            nome:
              type: string
              example: RICARDO STACIARINI PUTTINI
            curso:
              $ref: "#/components/schemas/Curso_Short" 
    PeriodoLetivo:
      type: object
      properties:
        ano:
          type: number
          format: int64
          example: 2025
        periodo:
          type: number
          format: int64
          example: 1
    Curso_Short:
      allOf: 
        - $ref: '#/components/schemas/Resource'
        - type: object
          properties:
            id:
              example: 6351
            codigo:
              type: string
              example: 6351
            nome:
              type: string
              example: 	ENGENHARIA DE REDES DE COMUNICAÇÃO
    Curriculo_Short:
      allOf: 
        - $ref: '#/components/schemas/Resource'
        - type: object
          properties:
            id:
              example: 6351-3
            codigo:
              type: string
              example: 6351-3
    Resource:
      type: object
      required:
        - resourceType
      properties:
        id:
          type: string
          description: id único da instânica
        resourceType:
          type: string
        lastUpdated:
          type: string
          format: date-time
      discriminator:
        propertyName: resourceType
        mapping:
          Aluno: '#/components/schemas/Aluno'
          Curso: '#/components/schemas/Curso'
          Curriculo: '#/components/schemas/Curriculo'
          Disciplina: '#/components/schemas/Disciplina'
          HistoricoAcademico: '#/components/schemas/HistoricoAcademico'
          Matricula: '#/components/schemas/Matricula'
          Turma: '#/components/schemas/Turma'
    SearchSet:
      type: object  
      required:
        - total
        - link
      properties:
        total:
          type: integer 
        count:
          type: integer
        offset:
          type: integer     
        link:
          type: object
          required:
            - self
          properties:
            self:
              type: string
            next:
              type: string
            previous:
              type: string
        items:
          type: array
          items:
            anyOf:
            - $ref: '#/components/schemas/Aluno_Short'
#            - $ref: '#/components/schemas/Curso'
#            - $ref: '#/components/schemas/Curriculo'
#            - $ref: '#/components/schemas/Disciplina'
#            - $ref: '#/components/schemas/Matricula'
#            - $ref: '#/components/schemas/Turma'            