openapi: 3.0.4
info:
  title: Matricula
  description: >-
    
  termsOfService: https://redes.unb.br/api/terms/
  contact:
    email: ricardo.puttini@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
  - url: /api/Matricula
tags:
  - name: Matricula
    description: 
paths:
  /:
    get:
      tags:
        - Matricula
      summary: 
      description: 
      operationId: search
      parameters:
        - name: periodoLetivo
          in: query
          description: período letivo da matrícula, p.e. 2026-1
          required: true
          schema:
            type: string
        - name: aluno
          in: query
          description: id (matricula) do aluno
          required: false
          schema:
            type: string
        - name: turma
          in: query
          description: id da turma
          required: false
          schema:
            type: string
        - name: status
          in: query
          description: status (lista) da matricula - em caso de mais de um valor, separar os valores por vírgula, p.e. matriculado,pre-matricula
          required: false
          schema:
            type: string
        - name: _elements
          in: query
          description: 'elemento principal presente nos objetos de retorno. Caso seja omitido, TODOS os objetos retornados conterão os elementos Matricula.aluno e Matricula.turma' 
          required: false
          schema:
            type: string
            enum:
              - aluno
              - turma
        - name: _count
          in: query
          description: 
          required: false
          schema:
            type: string
        - name: _offset
          in: query
          description: 
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchSet'
    post:
      tags:
        - Matricula
      summary: 
      description: 
      operationId: create
      requestBody:
        description: 
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Matricula_Create"
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Matricula'
        '400':
          description: Bad request
  /{id}:
    get:
      tags:
        - Matricula
      summary: 
      description: 
      operationId: read
      parameters:
        - name: id
          in: path
          description: id (matricula) do aluno
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Matricula'
    patch:
      tags:
        - Matricula
      summary: 
      description: 
      operationId: patch
      parameters:
        - name: id
          in: path
          description: id (matricula) do aluno
          required: true
          schema:
            type: string
      requestBody:
        description: 
        required: true
        content:
          application/json-patch+json:
            schema:
              $ref: "#/components/schemas/Matricula_Patch"
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Matricula'
        '400':
          description: Bad request
        '404':
          description: Not found  
components:
  schemas:
    Resource:
      type: object
      required:
        - resourceType
      properties:
        id:
          type: string
          description: id único da instânica
        resourceType:
          type: string
        lastUpdated:
          type: string
          format: date-time
      discriminator:
        propertyName: resourceType
        mapping:
          Aluno: '#/components/schemas/Aluno'
          Curso: '#/components/schemas/Curso'
          Curriculo: '#/components/schemas/Curriculo'
          Disciplina: '#/components/schemas/Disciplina'
          Matricula: '#/components/schemas/Matricula'
          Turma: '#/components/schemas/Turma'
    Matricula:
      allOf: 
        - $ref: '#/components/schemas/Resource'
        - type: object
          properties:
            id:
              type: string
            status:
              $ref: '#/components/schemas/status_Matricula'
            motivoIndeferimento:
              $ref: '#/components/schemas/motivoIndeferimento_Matricula'
            prioridade: 
              type: integer
            aluno:
              $ref: '#/components/schemas/Aluno_Short' 
            turma:
              $ref: '#/components/schemas/Turma_Short'  
    Matricula_Create:
      type: object
      required:
        - status
        - aluno
        - turma
      properties:
        status:
          type: string
          enum:
          - prematricula
          - pedido
        prioridade: 
          type: integer
          minimum: 1
          maximum: 10
          description: 'deve ser informado apenas se Matricula.status="pedido". Será ignorado, nos demais casos.'
        aluno:
          type: object
          properties:
            id:
              type: string
              description:
              example: 252100019
        turma:
          type: object
          properties:
            id:      
              type: string
              description:
    Matricula_Patch:
      type: array
      description: 'utilizar apenas o patch em "status" para os valores de status "matriculado", "retirado" e "retirado-coordenador"; utilizar o patch em "status" e "motivoIndeferimento" para o valor de status "indeferido"'
      items:
        oneOf:
        - type: object
          properties:
            op:
              type: string
              enum: 
              - replace
            path:
              type: string
              enum: 
              - '/status'
            value:
              type: string
              enum:
                - matriculado
                - retirado
                - indeferido
                - retirado-coordenador
        - type: object
          properties:
            op:
              type: string
              enum: 
              - add
            path:
              type: string
              enum: 
              - '/motivoIndeferimento'
            value:
              $ref: '#/components/schemas/motivoIndeferimento_Matricula'
        minItems: 1
        maxItems: 2
    Aluno_Short:
      allOf: 
        - $ref: '#/components/schemas/Resource'
        - type: object
          properties:
            id:
              type: string
              example: 252100019
            matricula:
              type: string
              example: 252100019
            nome:
              type: string
              example: RICARDO STACIARINI PUTTINI
    PeriodoLetivo:
      type: object
      properties:
        ano:
          type: number
          format: int64
          example: 2025
        periodo:
          type: number
          format: int64
          example: 1
    Turma_Short:
      allOf: 
        - $ref: '#/components/schemas/Resource'
        - type: object
          properties:
            id:
              type: string
            codigo:
              type: string
              example: 01
            vagasOfertadas:
              type: integer
              example: 	30
            vagasPreenchidas:
              type: integer
              example: 	26
            periodoLetivo:
              $ref: '#/components/schemas/PeriodoLetivo'
            disciplina:
              $ref: '#/components/schemas/Disciplina'   
    Disciplina:
      allOf: 
        - $ref: '#/components/schemas/Resource'
        - type: object
          properties:
            id:
              example: ENE0276
            codigo:
              type: string
              example: ENE0276
            nome:
              type: string
              example: METODOLOGIA E DESENVOLVIMENTO DE SOFTWARE 
            modalidade:
              type: string
              example: presencial
            cargaHorariaTotal:
              type: integer
              example: 60
    Disciplina_Matricula:
      allOf: 
        - $ref: '#/components/schemas/Disciplina'
        - type: object
          properties:
            mencao:
              type: string
              enum:
                - SS
                - MS
                - MM
                - MI
                - II
                - SR
            frequencia:
              type: integer
              example: 80
            status:
              $ref: '#/components/schemas/status_Matricula'
            periodoLetivo:
              $ref: '#/components/schemas/PeriodoLetivo'
    status_Matricula:
      type: string
      enum:
        - prematricula
        - retirado
        - matriculado
        - pedido
        - indeferido
        - retirado-coordenador
    motivoIndeferimento_Matricula:
      type: string
      enum:
        - creditos-excedidos
        - ja-matriculado
        - conflito-horario
        - vagas-excedidas
    SearchSet:
      type: object  
      required:
        - total
        - link
      properties:
        total:
          type: integer 
        count:
          type: integer
        offset:
          type: integer     
        link:
          type: object
          required:
            - self
          properties:
            self:
              type: string
            next:
              type: string
            previous:
              type: string
        items:
          type: array
          items:
            anyOf:
#            - $ref: '#/components/schemas/Aluno_Short'
#            - $ref: '#/components/schemas/Curso'
#            - $ref: '#/components/schemas/Curriculo'
#            - $ref: '#/components/schemas/Disciplina'
            - $ref: '#/components/schemas/Matricula'
#            - $ref: '#/components/schemas/Turma'            